import Head from 'next/head';
import First from 'components/home/section/first_section';
import CompletePackage from 'components/home/section/CompletePackage_Section';
import Portofolio from 'components/home/section/Portofolio_Section';
import Testimonial from 'components/home/section/Testimonial_Section';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Alba</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <First />
      <CompletePackage />
      <Portofolio />
      <Testimonial />
    </div>
  );
}
