import Head from 'next/head';
import First from 'components/home/section/First_Section';
import CompletePackage from 'components/home/section/CompletePackage_Section';
import Portofolio from 'components/home/section/Portofolio_Section';
import Testimonial from 'components/home/section/Testimonial_Section';
import Layout from 'components/layout/Layout';

export default function Home() {
  return (
    <Layout withFooter>
      <div>
        <Head>
          <title>Alba</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <First />
        <CompletePackage />
        <Portofolio />
        <Testimonial />
      </div>
    </Layout>
  );
}
